name: societyrun
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.5.5+49

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.1.2
  fluttertoast: ^8.2.2
  path_provider: ^2.0.5
  provider: ^6.0.1
  retrofit: ^3.3.1
  json_annotation: ^4.1.0
  dio_http_cache: ^0.3.0
  json_serializable: ^4.1.4
  dio: ^4.0.0
  connectivity: ^3.0.6
  flutter_svg: ^2.0.7
  otp_text_field: ^1.1.1
  ndialog: ^4.3.1
  file_picker: ^5.3.2
  razorpay_flutter: ^1.3.5
  get:
  get_it:
  flutter_html: ^3.0.0-beta.2
  flutter_share: ^2.0.0
  external_path: ^1.0.1
  image_picker: ^0.8.4+2
  permission_handler: ^10.4.3
  clipboard: ^0.1.3
  carousel_slider: ^4.0.0
  #firebase
  firebase_messaging: ^14.6.3
  firebase_core:
  firebase_analytics:
  flutter_local_notifications:  ^9.9.1
  notification_permissions: ^0.6.1
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_image_compress: ^2.0.3
  fluttercontactpicker: ^4.7.0
  device_apps: ^2.1.1
  flutter_launcher_icons: ^0.9.2
  logger:
  #flutter_launcher_naflutter_image_compressme: ^0.0.1
  package_info: ^2.0.2
  pie_chart: ^5.0.1
  webview_flutter: ^4.2.2
  dropdown_search: ^5.0.5
  #dropdown_plus: ^0.0.9
  flutter_switch: ^0.3.2
  rate_my_app: ^2.0.0
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.0.0+4
  uuid: ^3.0.5
  cached_network_image: ^3.1.0
  #flutter_statusbarcolor: 0.2.3
  dotted_border: ^2.0.0+1
  after_layout: ^1.1.0
  #flutter_full_pdf_viewer: ^1.0.6
  charts_flutter:
    git:
      url: https://github.com/devplanet-dp/charts.git
      path: charts_flutter
  open_file_safe: ^3.2.3
  syncfusion_flutter_pdfviewer:
  society_gatepass:
    git:
      url: https://zapniroshana@bitbucket.org/Convivialsoln/society_gatepass.git
  # amazon_cognito_identity_dart: ^0.0.22

  #intl_translation: ^0.17.1
  #retrofit_generator: 2.0.1+2
  build_runner: ^2.1.4
  #analyzer: ^2.6.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  file: ^6.1.4
  awesome_notifications: ^0.6.21
  device_info_plus: ^9.0.2
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:

  ffi: ^2.0.1
  intl: ^0.18.0

  #meta: ^1.3.0
 # intl: 0.17.0-nullsafety.2

flutter_icons:
  ios : true
  android : true
  image_path_ios : "assets/images/ic_societyrun.png"
  image_path_android : "assets/images/ic_societyrun.png"

flutter_launcher_name:
  name: "SocietyRun"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/audio/
    - assets/images/ic_societyrun.png
    - assets/images/society_run_green.png
    - assets/images/society_run_green.svg
    - assets/images/societyrun_icon.png
    - assets/images/ccavenue.jpg
    - i18n/en.json
    - i18n/hi.json
    - assets/other_assets/component_user_profile.png
    - assets/other_assets/profile_icon.svg
    - assets/other_assets/societyrun-logo_colored.svg
    - assets/other_assets/societyrun-logo.svg
    - assets/other_assets/Header_bg.svg
    - assets/other_assets/login_icon.svg
    - assets/other_assets/Classified_big_icon.svg
    - assets/other_assets/Top_breadcrum.svg
    - assets/other_assets/notification_icon.svg
    - assets/other_assets/building_icon.svg
    - assets/other_assets/gatePass_icon.svg
    - assets/other_assets/More_icon.svg
    - assets/other_assets/Services_icon.svg
    - assets/other_assets/shopping_icon.svg
    - assets/other_assets/Shop_icon.svg
    - assets/other_assets/Support_icon.svg
    - assets/other_assets/store_icon.svg
    - assets/other_assets/while_bg.svg
    - assets/other_assets/Icon awesome-file-image.svg
    - assets/other_assets/Icon awesome-file-pdf.svg
    - assets/menu_assets/myhome_icon.svg
    - assets/menu_assets/building_icon_menu.svg
    - assets/menu_assets/service_icon_menu.svg
    - assets/menu_assets/club_icon_menu.svg
    - assets/menu_assets/gatepass_icon_menu.svg
    - assets/menu_assets/Support_icon_menu.svg
    - assets/menu_assets/admin_icon_menu.svg
    - assets/menu_assets/settings.svg
    - assets/menu_assets/switch.svg
    - assets/bottom_menu/bottom_bg.svg
    - assets/bottom_menu/bottom_building_icon.svg
    - assets/bottom_menu/bottom_club_icon.svg
    - assets/bottom_menu/bottom_home_icon.svg
    - assets/bottom_menu/bottom_menu_icon.svg
    - assets/bottom_menu/bottom_myhome_icon.svg
    - assets/bottom_menu/bottom_service_icon.svg
    - assets/other_assets/credit_card.png
    - assets/other_assets/about_us.svg
    - assets/other_assets/coming_soon.png
    - assets/other_assets/bike.svg
    - assets/other_assets/change_password.svg
    - assets/other_assets/success.svg
    - assets/other_assets/failure.svg
    - assets/other_assets/deactive.svg
    - assets/other_assets/taxi.svg
    - assets/other_assets/visitor.svg
    - assets/other_assets/delivery_man.svg
    - assets/other_assets/in.svg
    - assets/other_assets/out.svg
    - assets/other_assets/splash_socityrun.png
    - assets/other_assets/anxiety.svg
    - assets/other_assets/expense.svg
    - assets/other_assets/paytm.png
    - assets/other_assets/razorpay.png
    - assets/other_assets/app_settings.svg
    - assets/other_assets/in_app_call.svg
    - assets/other_assets/daily_helps.svg
    - assets/other_assets/logout_icon.svg
    - assets/other_assets/guest.svg
    - assets/other_assets/feedback.svg
    - assets/other_assets/verified_contact.svg
    - assets/other_assets/t3_ic_wp.svg
    - assets/other_assets/no_data_found.png
    - assets/other_assets/paid.png
    - assets/other_assets/document_image.svg
    - assets/other_assets/active_user.png
    - assets/other_assets/smile.png
    - assets/other_assets/sad.png
    - assets/other_assets/email.svg
    - assets/other_assets/receipt.svg
    - assets/other_assets/user.png
    - assets/other_assets/notAllowed.svg
    - assets/other_assets/bachelors.svg
    - assets/other_assets/family.svg
    - assets/other_assets/commercial.svg
    - assets/other_assets/refer.svg
    - assets/other_assets/rate.svg
    - assets/other_assets/already_paid.png
    - assets/other_assets/user_management.svg
    - shorebird.yaml
  fonts:
    - family: sans-serif
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # git clone https://Convivialsoln@bitbucket.org/Convivialsoln/societyrun.git
