import 'package:json_annotation/json_annotation.dart';

@JsonSerializable()
class Announcement {
  String ID,
      USER_NAME,
      USER_PHOTO,
      SUBJECT,
      DESCRIPTION,
      ATTACHMENT,
      CATEGORY,
      EXPIRY_DATE,
      POLL_Q,
      C_DATE,
      table_name,
      ANS,
      votes,
      START_DATETIME,
      END_DATETIME,
      Start_Time,
      VENUE,
      ACHIEVER_NAME,
      ALLOW_COMMENT,
      DISPLAY_COMMENT_ALL,
      SEND_TO,
      SECRET_POLL,
      VOTING_RIGHTS,
      POST_AS,
      STATUS,
      Cancel_By,
      Cancel_Date,
      START_DATE,
      END_DATE,
      START_TIME,
      END_TIME,BLOCK,FLAT;

  Announcement(
      {this.ID,
      this.USER_NAME,
      this.USER_PHOTO,
      this.SUBJECT,
      this.DESCRIPTION,
      this.ATTACHMENT,
      this.CATEGORY,
      this.EXPIRY_DATE,
      this.POLL_Q,
      this.C_DATE,
      this.table_name,
      this.ANS,
      this.votes,
      this.START_DATETIME,
      this.END_DATETIME,
      this.Start_Time,
      this.VENUE,
      this.ACHIEVER_NAME,
      this.ALLOW_COMMENT,
      this.DISPLAY_COMMENT_ALL,
      this.SEND_TO,
      this.SECRET_POLL,
      this.VOTING_RIGHTS,
      this.POST_AS,
      this.STATUS,
      this.Cancel_By,
      this.Cancel_Date,
      this.START_DATE,
      this.END_DATE,
      this.START_TIME,
      this.END_TIME,this.BLOCK,this.FLAT});

  factory Announcement.fromJson(Map<String, dynamic> json) {
    return Announcement(
        ID: json["ID"],
        USER_NAME: json["USER_NAME"],
        USER_PHOTO: json["USER_PHOTO"],
        SUBJECT: json["SUBJECT"],
        DESCRIPTION: json["DESCRIPTION"],
        ATTACHMENT: json["ATTACHMENT"],
        CATEGORY: json["CATEGORY"],
        EXPIRY_DATE: json["EXPIRY_DATE"],
        POLL_Q: json["POLL_Q"],
        C_DATE: json["C_DATE"],
        table_name: json["table_name"],
        ANS: json["ANS"],
        votes: json["votes"],
        START_DATETIME: json["START_DATETIME"],
        END_DATETIME: json["END_DATETIME"],
        Start_Time: json["Start_Time"],
        VENUE: json["VENUE"],
        ACHIEVER_NAME: json["ACHIEVER_NAME"],
        ALLOW_COMMENT: json["ALLOW_COMMENT"],
        DISPLAY_COMMENT_ALL: json["DISPLAY_COMMENT_ALL"],
        SEND_TO: json["SEND_TO"],
        SECRET_POLL: json["SECRET_POLL"],
        VOTING_RIGHTS: json["VOTING_RIGHTS"],
        POST_AS: json["POST_AS"],
        STATUS: json["STATUS"],
        Cancel_By: json["Cancel_By"],
        Cancel_Date: json["Cancel_Date"],
        START_DATE: json["START_DATE"],
        END_DATE: json["END_DATE"],
        START_TIME: json["START_TIME"],
        END_TIME : json["END_TIME"],
        BLOCK:json["BLOCK"],
        FLAT: json["FLAT"]);
  }
}
